name: Clang Format

on:
  push:
    branches: [ main ]
    paths:
      - '.github/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'examples/**'
      - '.clang-format'
  pull_request:
    branches: [ main ]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - 'include'
          - 'src'
          - 'tests'
          - 'examples'
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.0.0
      with:
        clang-format-version: '12'
        check-path: ${{ matrix.path }}
